# Generated by Django 4.2.1 on 2023-05-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('title', models.CharField(default=False, max_length=100, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GitRepo',
            fields=[
                ('url', models.URLField(default=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default=False, max_length=100)),
                ('description', models.CharField(default=False, max_length=500)),
                ('image', models.URLField(default=False)),
                ('languages', models.ManyToManyField(blank=True, default=False, to='core.language')),
            ],
        ),
    ]
