# Generated by Django 4.2.1 on 2023-06-06 19:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_gitrepo_description_alter_gitrepo_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=500)),
                ('url', models.URLField(blank=True, default='')),
                ('image', models.URLField(default='')),
                ('state', models.CharField(choices=[('Completed', 'COMPLETED'), ('In-progress', 'IN_PROGRESS'), ('Not-stared', 'NOT_STARTED')], max_length=100)),
                ('certificate', models.URLField(default='')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
