# Generated by Django 4.2.1 on 2023-06-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='certificate',
            field=models.URLField(blank=True, default=''),
        ),
    ]
