# Generated by Django 4.2.1 on 2023-06-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_education_title_alter_gitrepo_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='certificate',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='education',
            name='image',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='gitrepo',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='gitrepo',
            name='image',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='gitrepo',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='gitrepo',
            name='url',
            field=models.URLField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='color',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='language',
            name='title',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
